### ISSUE TITLE
Heather Douglas: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by claxtonh** [mbjones/codemeta#18]
Hello, I'm a science researcher in biochemistry, and I see the need for accessible, reusable, code in the fields of science.  I'd like to see more professors cite the code that they use as a means of increasing reproducibility in science.<p><br><blockquote>This issue was created by @claxtonh via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by acabunoc** [comment]
Thanks @claxtonh! 

You can take a look at what's happening in the space:
* **Code as a Research Object** blog posts:
    * [Code as a research object: updates, prototypes, next steps](http://mozillascience.org/code-as-a-research-object-updates-prototypes-next-steps/)
    * [What else is needed for code reuse](http://mozillascience.org/what-else-is-needed-for-code-reuse/)
    * [JSON-LD for software discovery, reuse and credit](http://www.arfon.org/json-ld-for-software-discovery-reuse-and-credit)

* [JSON-LD.org](http://json-ld.org/)
* [Schema.org](http://schema.org/)

Take a look at our jsonld schema: https://github.com/mbjones/codemeta/blob/master/codemeta.jsonld. Let us know if you think this would be a good representation of software!

We also have a few disucssions going on:
* [(JSON-LD) Metadata for software discovery](https://github.com/mozillascience/code-research-object/issues/15)
* [How should software be cited?](https://github.com/mozillascience/code-research-object/issues/12)
* [What information is needed to reuse code?](https://github.com/mozillascience/code-research-object/issues/2)
