### ISSUE TITLE
zuzzzu54: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by zuzzzu54** [mbjones/codemeta#21]
<p><br><blockquote>This issue was created by @zuzzzu54 via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbjones** [comment]
@zuzzzu54 your contributions are welcome.  Feel free to describe more where your interests lie in this ticket, or in any of the other outstanding issues.
