### ISSUE TITLE
Nicolaie Constantinescu: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by kosson** [mbjones/codemeta#22]
Hi,

I'm interested in how to look at code or simple data structures as bases for puzzle-like interconnectivity among peers. On short if I write a piece of code, what would be the common data exchange path I should take in order for my app / code to talk with other's code.
This activity here looks promising.

<p><br><blockquote>This issue was created by @kosson via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbjones** [comment]
@kosson I'm not exactly sure what you mean by 'data exchange path' -- most software has multiple mechanisms available for data exchange, and each supports a different subset.  In this project we are focusing more on how to build an interoperable and machine readable description of the software and its dependencies.  We do include a description of inputs and outputs to the software in our crosswalks, but that doesn't really cover *how* data is exchanged, but rather *what* data is exchanged. I think what you are looking for is more like a structural provenance description.  I'd be curious if our work on [ProvONE](purl.dataone.org/provone-v1-dev) covers part of what you are looking for?

**Comment by mbjones** [comment]
@kosson your contributions are welcome.
