### ISSUE TITLE
Nicolas P. Rougier: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by rougier** [mbjones/codemeta#23]
Hello,

I'm in the process (with @khinsen) of creating a peer-reviewed scientific journal that lives on github and which is dedicated to the replication of results in computational science. It is not yet officially open but you can get a better idea at https://github.com/ReScience/ReScience/wiki. 
We're currently in the process of testing the review system to check if will allow us to ultimately publish an article with the associated DOI through Zenodo (https://github.com/ReScience/ReScience-submission/pull/3).

I've just stumbled upon your project and while I'm not sure how I can help, I would be definitely interested in following your progress and integrate the proposed standardized metadata it in the journal.

Nicolas<p><br><blockquote>This issue was created by @rougier via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbjones** [comment]
@rougier Fantastic -- there's a list of outstanding issues in the issue tracker, and lots of interesting cross-walk work to be done.  Feel free to just follow along, or let us know if you're interested in more actively engaging in the comparison work on any of those tasks.
